[package]
name = "odjitter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
csv = "1.1.6"
geo = "0.18.0"
geo-types = "0.7.2"
geojson = { version = "0.22.2", features = ["geo-types"] }
rand = "0.8.4"
serde_json = "1.0.73"
